config/routes.rb
Moviemania::Application.routes.draw do

	resources :admins, :only => [:new, :create, :destroy]

  root 'pages#home'
  get "/movies",				:to => 'pages#movies'
  get "/schedule",			:to => 'pages#schedule'
  get "/contacts",			:to => 'pages#contacts'
  get "/about",					:to => 'pages#about'
  get "/help",					:to => 'pages#help'
  get "/contactus",			:to => 'pages#contactus'

  get "/login",						:to => 'admins#new'
  get "/create",				:to => 'admins#create'
  get "/logout",				:to => 'admins#destroy'

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def new
  	@title = "Login"
  end

  def create
  	@title = "New Admin"
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
  end

  def movies
  	@title ="Movies"
  end

  def schedule
  	@title = "Schedule"
  end

  def contacts
  	@title = "Contacts"
  end

  def about
  	@title = "About"
  end

  def help
  	@title = "Help"
  end

  def contactus
  	@title = "Contact Us"
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admins/create.html.erb
<h1>Admins#create</h1>
<p>Find me in app/views/admins/create.html.erb</p>

app/views/admins/destroy.html.erb
<h1>Admins#destroy</h1>
<p>Find me in app/views/admins/destroy.html.erb</p>

app/views/admins/new.html.erb
<h1>Admins#new</h1>
<p>Find me in app/views/admins/new.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="round">
	<div class="row">
		<div class="twelve columns">
			<hr />
			<div class="row">
				<div class="six columns">
					<p>&copy; 2013 MovieMania, Inc. All rights reserved</p>
				</div>
				<div class="six columns">
				<div id="navcontainer">
					<ul class="link-list">
						<li><%= link_to "ABOUT", about_path %></li>
						<li><%= link_to "BLOG", '#'%></li>
						<li><%= link_to "NEWS & EVENTS", '#'%></li>
						<li><%= link_to "CONTACT US", contacts_path %></li>
						<li><%= link_to "HELP", help_path %></li>
						<li><%= link_to image_tag("twitter.jpg", :alt => 'twitter', :class => "round", :width => 30, :height => 30), 'https://twitter.com' %></li>
						<li><%= link_to image_tag("facebook.png", :alt => 'facebook', :class => "round", :width => 35, :height => 35), 'https://facebook.com' %>
					</ul>
					</div>
				</div>
			</div>
		</div>
	</div>

	<p>
		Powered by: <%= link_to "Something Goes Here ", 'https://somethinggoeshere.com/' %>
		Developed at: <%= link_to "Something Else Goes Here", 'https://somethingelsegoeshere.com' %>
	</p>

</footer>

app/views/layouts/_header.html.erb
<!--The header section of the page-->
<header class="round">
	<nav class="top-bar round">
			<ul class="title-area">
			<!--Title Area-->
			<li class="name">
				<h3><%= link_to "  MovieMania", root_path %> </h3>
			</li>
		</ul>

		<section class="top-bar-section">
			<ul class="right">
				<li class="divider"></li>
				<li>
					<%= link_to "Home", root_path %>
				</li>
				<li class="divider"></li>
				<li class="has-dropdown">
					<%= link_to "Movies", movies_path %>
					<ul class="dropdown">
						<li><%= link_to "Now Showing", '#' %></li>
						<li><%= link_to "Coming Soon", '#' %></li>
					</ul>
				</li>
				<li class="divider"></li>
				<li>
					<%= link_to "Schedule", schedule_path %>
				</li>
				<li class="divider"></li>
				<li><%= link_to "About", about_path %></li>
				<li class="divider"></li>
				<li><%= link_to "Help", help_path %></li>
				<li class="divider"></li>
				<li><%= link_to "Contact Us", contactus_path %></li>
				<li class="divider"></li>
				<li><%= link_to "Login", login_path %></li>
			</ul>
		</section>

	</nav>

	<div class="row">
		<div class="small-3 columns">
				<%= link_to image_tag("logo.png", :alt=> "MovieMania", :class => "round", :width => 150, :height => 100, :caption => "MovieMania"), root_path %>
			</div>
			<div class="small-9 columns">
				<p>

				The home of movies. The home of movies. The home of movies.
				</p>
			</div>
		</div>
		<hr />

</header>

app/views/layouts/_stylesheets.html.erb
<!--Bringing Internet Explorer up to speed with HTML5-->
    <!--[if lt IE 9]>
    	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "stylesheet/custom.css" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : title %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  	<%= render "layouts/header" %>

  	<div class="container">

    	<%= yield %>

  	</div>

  	<%= render "layouts/footer" %>

    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contacts.html.erb
<div class="row">
	<div class="twelve columns">
		<div class="panel callout radius center">
			<h3>Contacts</h3>
		</div>
	</div>
</div>

<div class="row">
	<div class="twelve columns">
		<div class="panel round">
			<p>
				A panel is a simple, helpful Foundation component that enables you to outline sections of your page easily. This allows you to view your page sections as you add content to them or add emphasis to a section. The width is controlled by the grid columns you put them inside.
			</p>
		</div>
	</div>
</div>

app/views/pages/contactus.html.erb
<div class="row">
	<div class="twelve columns">
		<div class="panel callout radius center">
			<h3>Contact Us</h3>
		</div>
	</div>
</div>

<div class="row">

  <div class="small-3 columns">
  	<div class="panel">
  		<p>Image goes here</p>
  	</div>
  </div>
  <div class="small-9 columns">
  	<div class="panel">
  		<p>Profile and contacts goes here</p>
  	</div>
  </div>

  <div class="small-3 columns">
  	<div class="panel">
  		<p>Image goes here</p>
  	</div>
  </div>
  <div class="small-9 columns">
  	<div class="panel">
  		<p>Profile and contacts goes here</p>
  	</div>
  </div>

  <div class="small-3 columns">
  	<div class="panel">
  		<p>Image goes here</p>
  	</div>
  </div>
  <div class="small-9 columns">
  	<div class="panel">
  		<p>Profile and contacts goes here</p>
  	</div>
  </div>

</div>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<div class="row">
	<div class="twelve columns">

		<!-- Orbit Container -->
		<div class="orbit-container round size">
			<ul data-orbit="">
				<li>
					<%= image_tag "slider/demo1.jpg", :width => 970, :height => 540 %>
					<div class="orbit-caption">demo1.jpg</div>
				</li>

				<li>
					<%= image_tag "slider/demo2.jpg", :width => 970, :height => 540 %>
					<div class="orbit-caption">demo2.jpg</div>
				</li>

				<li>
					<%= image_tag "slider/demo3.jpg", :width => 970, :height => 540 %>
					<div class="orbit-caption">demo3.jpg</div>
				</li>
			</ul>
		</div>



	</div>
</div>

app/views/pages/movies.html.erb
<h1>Pages#movies</h1>
<p>Find me in app/views/pages/movies.html.erb</p>

app/views/pages/schedule.html.erb
<div class="row">
	<div class="twelve columns">
		<div class="panel callout radius center">
			<h3>Schedule</h3>
		</div>
	</div>
</div>

<div class="row">
	<div class="large-6 columns">
		<div class="panel round">
			<p>
				The day schedule goes here. <br />
				The day schedule goes here. <br />
				The day schedule goes here. <br />
				The day schedule goes here. <br />
				The day schedule goes here. <br />
				The day schedule goes here. <br />
				The day schedule goes here.
			</p>
		</div>
	</div>

	<div class="large-6 columns">
		<div class="panel round">
			<iframe src="https://www.google.com/calendar/embed?src=developer.ronnie%40gmail.com&ctz=Africa/Nairobi" style="border: 0" width="400" height="300" frameborder="0" scrolling="no"></iframe>
		</div>
	</div>
</div>